### PR TITLE
Fix session not persisted after login on page reload

### LINKED ISSUE #116: CORS Missing Allow Origin With AgencyOS and Directus
I've freshly installed Directus with AgencyOS and I'm getting CORS Missing Allow Origin when navigating through the pages.

If I reload the page then it loads, but when navigating for example using the menu, it returns CORS Missing Allow Origin.

Test url: https://new.reputazi.com/

### LINKED ISSUE #117: User not staying logged in after page refresh
Right now if the user logs in all the requests via the SDK are working as your authenticated but if you press F5 the user gets thrown back to the login even if the refresh_token cookie is set. You can try this on your own domain https://www.agencyos.dev/ (even tough you need to set the domain in directus to www.agencyos.dev as it currently cant set the cookie). Before you used a custom CookieStorage with type JSON when authenticating with the SDK but now with mode Cookie it still doesnt work.

Do you have any idea on how to fix this?

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
- Proxy all directus requests to circumvent any CORs rule issues
- Prefer session mode over cookie/json
- Utilize `/user/me` over local token fetch as sdk auto renews

Fixes #117 
Fixes #116

### CODE REVIEW

File: modules/directus/index.ts [hunk 1]
```diff
@@ -49,6 +50,8 @@ export default defineNuxtModule({
 			log.warn(`Please make sure to set Directus baseUrl`);
 		}
 
+		const config = useRuntimeConfig();
```
Comment (bryantgillespie) [inline modules/directus/index.ts:53]: You can't use the composable in a module.
https://nuxt.com/docs/guide/going-further/modules#exposing-options-to-runtime

You have to access through the module options or the Nuxt App like this 

```
nuxt.options.runtimeConfig.public.myModule
```

**Review by bryantgillespie — CHANGES_REQUESTED** [review]
Looks pretty solid. Nice work. Just need to update the runtime config bit in the module.

File: modules/directus/index.ts (hunk 1 above)
Comment (ComfortablyCoding) [reply modules/directus/index.ts]: Good catch! I must have confused it with plugins.

**Review by bryantgillespie — APPROVED** [review]
Send it 🚀
